language: node_js
node_js:
  - '18'
services:
  - mongodb
cache: 
  directories:
    - node_modules
branches:
  only:
    - master
env:
  global:
    - PORT=3000
    - MONGODB_URL=mongodb://localhost:27017/librenews
    - JWT_SECRET=thisisasamplesecret
    - JWT_ACCESS_EXPIRATION_MINUTES=30
    - JWT_REFRESH_EXPIRATION_DAYS=30
script:
  - npm run lint
  - npm run test
after_success: npm run coverage:coveralls
